# permissions for end users to edit recommenderobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recommenderobject-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: maverick
    app.kubernetes.io/part-of: maverick
    app.kubernetes.io/managed-by: kustomize
  name: recommenderobject-editor-role
rules:
- apiGroups:
  - recommender.maverick.com
  resources:
  - recommenderobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recommender.maverick.com
  resources:
  - recommenderobjects/status
  verbs:
  - get
